import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from '@/context/QueryContext/QueryProvider';
import { UserProvider } from '@/context/UserContext/UserContext'; // ✅ Đảm bảo đúng path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EverGreen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <UserProvider>
            {children}
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
